version: "3"
services:
  twc3sim:
    container_name: twc3simv2
    image: thekey82/twc3simulator_v2
    environment:
      - "SHELLY_IP=192.168.178.205"
    restart: unless-stopped

  evcc:
    command:
      - evcc
    container_name: evcc
    image: evcc/evcc
    ports:
      - 7070:7070/tcp
      - 8887:8887/tcp
      - 7090:7090/udp
      - 9522:9522/udp
    depends_on:
      - twc3sim
    volumes:
      - ./evcc.yaml:/etc/evcc.yaml
      - ./data:/root/.evcc
    restart: unless-stopped
